spin_manifest_version = 2

[application]
name = "order-processor"
version = "0.1.0"
authors = ["Radu Matei <radu@fermyon.com>"]

[variables]
dapr_host = { default = "http://localhost" }
dapr_port = { default = "5003" }


[[trigger.http]]
route = "/orders/..."
component = "order-processor"

[component.order-processor]
source = "target/order-processor.wasm"
[component.order-processor.variables]
dapr_host = "{{ dapr_host }}"
dapr_port = "{{ dapr_port }}"
[component.order-processor.build]
command = "npm run build"
watch = ["src/**/*.ts"]
